#############################################################################
# Makefile for building: libguicore.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? 12? 30 22:02:15 2010
# Project:  guicore.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile guicore.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4 -Iinclude -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -shared -Wl,-soname,libguicore.so.1
LIBS          = $(SUBLIBS)  -L/usr/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = tmpobj/x86/

####### Files

SOURCES       = src/dt_button.cpp \
		src/dt_cachebmp.cpp \
		src/dt_combox.cpp \
		src/dt_commctrl.cpp \
		src/dt_ctrl.cpp \
		src/dt_edit.cpp \
		src/dt_icon.cpp \
		src/dt_icongroup.cpp \
		src/dt_listbox.cpp \
		src/dt_listview.cpp \
		src/dt_skinbutton.cpp \
		src/dt_skinchkbutton.cpp \
		src/dt_skinctrl.cpp \
		src/dt_skinlable.cpp \
		src/dt_static.cpp \
		src/SkinForm.cpp \
		src/dt_ipaddr.cpp \
		src/dt_font.cpp 
OBJECTS       = tmpobj/x86/dt_button.o \
		tmpobj/x86/dt_cachebmp.o \
		tmpobj/x86/dt_combox.o \
		tmpobj/x86/dt_commctrl.o \
		tmpobj/x86/dt_ctrl.o \
		tmpobj/x86/dt_edit.o \
		tmpobj/x86/dt_icon.o \
		tmpobj/x86/dt_icongroup.o \
		tmpobj/x86/dt_listbox.o \
		tmpobj/x86/dt_listview.o \
		tmpobj/x86/dt_skinbutton.o \
		tmpobj/x86/dt_skinchkbutton.o \
		tmpobj/x86/dt_skinctrl.o \
		tmpobj/x86/dt_skinlable.o \
		tmpobj/x86/dt_static.o \
		tmpobj/x86/SkinForm.o \
		tmpobj/x86/dt_ipaddr.o \
		tmpobj/x86/dt_font.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		guicore.pro
QMAKE_TARGET  = guicore
DESTDIR       = lib/libpc/
TARGET        = libguicore.so.1.0.0
TARGETA       = lib/libpc/libguicore.a
TARGETD       = libguicore.so.1.0.0
TARGET0       = libguicore.so
TARGET1       = libguicore.so.1
TARGET2       = libguicore.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  lib/libpc/$(TARGET)

lib/libpc/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) lib/libpc/ || $(MKDIR) lib/libpc/ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) lib/libpc/$(TARGET)
	-$(DEL_FILE) lib/libpc/$(TARGET0)
	-$(DEL_FILE) lib/libpc/$(TARGET1)
	-$(DEL_FILE) lib/libpc/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) lib/libpc/



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: guicore.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile guicore.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile guicore.pro

dist: 
	@$(CHK_DIR_EXISTS) tmpobj/x86/guicore1.0.0 || $(MKDIR) tmpobj/x86/guicore1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmpobj/x86/guicore1.0.0/ && $(COPY_FILE) --parents src/dt_button.cpp src/dt_cachebmp.cpp src/dt_combox.cpp src/dt_commctrl.cpp src/dt_ctrl.cpp src/dt_edit.cpp src/dt_icon.cpp src/dt_icongroup.cpp src/dt_listbox.cpp src/dt_listview.cpp src/dt_skinbutton.cpp src/dt_skinchkbutton.cpp src/dt_skinctrl.cpp src/dt_skinlable.cpp src/dt_static.cpp src/SkinForm.cpp src/dt_ipaddr.cpp src/dt_font.cpp tmpobj/x86/guicore1.0.0/ && (cd `dirname tmpobj/x86/guicore1.0.0` && $(TAR) guicore1.0.0.tar guicore1.0.0 && $(COMPRESS) guicore1.0.0.tar) && $(MOVE) `dirname tmpobj/x86/guicore1.0.0`/guicore1.0.0.tar.gz . && $(DEL_FILE) -r tmpobj/x86/guicore1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) lib/libpc/$(TARGET) 
	-$(DEL_FILE) lib/libpc/$(TARGET0) lib/libpc/$(TARGET1) lib/libpc/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

tmpobj/x86/dt_button.o: src/dt_button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_button.o src/dt_button.cpp

tmpobj/x86/dt_cachebmp.o: src/dt_cachebmp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_cachebmp.o src/dt_cachebmp.cpp

tmpobj/x86/dt_combox.o: src/dt_combox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_combox.o src/dt_combox.cpp

tmpobj/x86/dt_commctrl.o: src/dt_commctrl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_commctrl.o src/dt_commctrl.cpp

tmpobj/x86/dt_ctrl.o: src/dt_ctrl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_ctrl.o src/dt_ctrl.cpp

tmpobj/x86/dt_edit.o: src/dt_edit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_edit.o src/dt_edit.cpp

tmpobj/x86/dt_icon.o: src/dt_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_icon.o src/dt_icon.cpp

tmpobj/x86/dt_icongroup.o: src/dt_icongroup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_icongroup.o src/dt_icongroup.cpp

tmpobj/x86/dt_listbox.o: src/dt_listbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_listbox.o src/dt_listbox.cpp

tmpobj/x86/dt_listview.o: src/dt_listview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_listview.o src/dt_listview.cpp

tmpobj/x86/dt_skinbutton.o: src/dt_skinbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_skinbutton.o src/dt_skinbutton.cpp

tmpobj/x86/dt_skinchkbutton.o: src/dt_skinchkbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_skinchkbutton.o src/dt_skinchkbutton.cpp

tmpobj/x86/dt_skinctrl.o: src/dt_skinctrl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_skinctrl.o src/dt_skinctrl.cpp

tmpobj/x86/dt_skinlable.o: src/dt_skinlable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_skinlable.o src/dt_skinlable.cpp

tmpobj/x86/dt_static.o: src/dt_static.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_static.o src/dt_static.cpp

tmpobj/x86/SkinForm.o: src/SkinForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/SkinForm.o src/SkinForm.cpp

tmpobj/x86/dt_ipaddr.o: src/dt_ipaddr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_ipaddr.o src/dt_ipaddr.cpp

tmpobj/x86/dt_font.o: src/dt_font.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmpobj/x86/dt_font.o src/dt_font.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

